<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net46</TargetFramework>
    <AssemblyName>WeNeedMoreNoels</AssemblyName>
    <Product>Multiplayer-AliceInCradle</Product>
    <Version>1.0.0</Version>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <LangVersion>latest</LangVersion>
    <RestoreAdditionalProjectSources>
      https://api.nuget.org/v3/index.json;
      https://nuget.bepinex.dev/v3/index.json;
      https://nuget.samboy.dev/v3/index.json
    </RestoreAdditionalProjectSources>
    <RootNamespace>WeNeedMoreNoels</RootNamespace>
    <OutputPath>E:\WeNeedMoreNoels\AliceInCradle_ver029-BeplnEx\BepInEx\plugins\WNMN</OutputPath>
	<AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
	<AppendRuntimeIdentifierToOutputPath>false</AppendRuntimeIdentifierToOutputPath>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="BepInEx.Analyzers" Version="1.*" PrivateAssets="all" />
    <PackageReference Include="BepInEx.Unity.Mono" Version="6.0.0-be.*" IncludeAssets="compile" />
    <PackageReference Include="BepInEx.PluginInfoProps" Version="2.*" />
    <PackageReference Include="LiteNetLib" Version="0.9.5.2" />
    <PackageReference Include="protobuf-net" Version="2.4.9" />
    <PackageReference Include="System.Reflection" Version="4.3.0" />
	<PackageReference Include="UnityEngine.Modules" Version="2022.3.62" IncludeAssets="compile" />
    <PackageReference Include="Krafs.Publicizer" Version="2.3.0" PrivateAssets="all" />
  </ItemGroup>
  
  <ItemGroup>
    <Publicize Include="Assembly-CSharp" />
    <Publicize Include="unsafeAssem" />
    <Publicize Include="ttr" />
  </ItemGroup>

  <ItemGroup Condition="'$(TargetFramework.TrimEnd(`0123456789`))' == 'net'">
    <PackageReference Include="Microsoft.NETFramework.ReferenceAssemblies" Version="1.0.2" PrivateAssets="all" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="Assembly-CSharp">
      <HintPath>..\..\WeNeedMoreNoels\AliceInCradle_ver029-BeplnEx\AliceInCradle_Data\Managed\Assembly-CSharp.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="Fusion.Common">
      <HintPath>..\..\WeNeedMoreNoels\AliceInCradle_ver029-BeplnEx\AliceInCradle_Data\Managed\Fusion.Common.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="Fusion.Runtime">
      <HintPath>..\..\WeNeedMoreNoels\AliceInCradle_ver029-BeplnEx\AliceInCradle_Data\Managed\Fusion.Runtime.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="mscorlib">
      <HintPath>..\..\WeNeedMoreNoels\AliceInCradle_ver029-BeplnEx\AliceInCradle_Data\Managed\mscorlib.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="netstandard">
      <HintPath>..\..\WeNeedMoreNoels\AliceInCradle_ver029-BeplnEx\AliceInCradle_Data\Managed\netstandard.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="Newtonsoft.Json">
      <HintPath>..\..\WeNeedMoreNoels\AliceInCradle_ver029-BeplnEx\AliceInCradle_Data\Managed\Newtonsoft.Json.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="pixelliner">
      <HintPath>..\..\WeNeedMoreNoels\AliceInCradle_ver029-BeplnEx\AliceInCradle_Data\Managed\pixelliner.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="System.Reflection">
      <HintPath>C:\Users\Administrator\.nuget\packages\system.reflection\4.3.0\lib\net462\System.Reflection.dll</HintPath>
      <Private>True</Private>
    </Reference>
    <Reference Include="unsafeAssem">
      <HintPath>..\..\WeNeedMoreNoels\AliceInCradle_ver029-BeplnEx\AliceInCradle_Data\Managed\unsafeAssem.dll</HintPath>
      <Private>False</Private>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <None Update="en\en_wnmn_localization.txt">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="pxls\noel_inverse.px.dat">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="pxls\noel_inverse.pxl.dat">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="pxls\noel_inverse.manifest">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="pxls\noel_inverse.pxl.manifest">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="pxls\noel_inverse.pxls.bytes.texture_0.dat">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="pxls\noel_inverse.pxls.bytes.texture_0.manifest">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="pxls\noel_inverse.pxls.dat">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="pxls\noel_inverse.pxls.manifest">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="pxls\noel_inverse_magic.pxl.dat">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="pxls\noel_inverse_magic.manifest">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="pxls\noel_inverse_magic.pxl.manifest">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="pxls\noel_inverse_magic.pxls.bytes.texture_0.dat">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="pxls\noel_inverse_magic.pxls.bytes.texture_0.manifest">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="pxls\noel_inverse_magic.pxls.dat">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="pxls\noel_inverse_magic.pxls.manifest">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="pxls\noel_inverse_r1.pxl.dat">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="pxls\noel_inverse_r18.pxl.dat">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="pxls\noel_inverse_r18.manifest">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="pxls\noel_inverse_r18.pxl.manifest">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="pxls\noel_inverse_r18.pxls.bytes.texture_0.dat">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="pxls\noel_inverse_r18.pxls.bytes.texture_0.manifest">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="pxls\noel_inverse_r18.pxls.dat">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="pxls\noel_inverse_r18.pxls.manifest">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="resources\multiplayer.dat">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="resources\multiplayer.manifest">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="zh-cn\zh-cn_wnmn_localization.txt">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="zh-tc\zh-tc_wnmn_localization.txt">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>

  <ItemGroup>
    <Folder Include="pxls\" />
  </ItemGroup>

  <ItemGroup>
    <Reference Update="System">
      <Private>False</Private>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <Reference Update="System.Core">
      <Private>False</Private>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <Reference Update="System.Data">
      <Private>False</Private>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <Reference Update="System.Drawing">
      <Private>False</Private>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <Reference Update="System.IO.Compression.FileSystem">
      <Private>False</Private>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <Reference Update="System.Numerics">
      <Private>False</Private>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <Reference Update="System.Runtime.Serialization">
      <Private>False</Private>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <Reference Update="System.Xml">
      <Private>False</Private>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <Reference Update="System.Xml.Linq">
      <Private>False</Private>
    </Reference>
  </ItemGroup>
</Project>
