<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <AssemblyName>WeNeedMoreNoels</AssemblyName>
    <Product>Multiplayer-AliceInCradle</Product>
    <Version>1.0.0</Version>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <LangVersion>latest</LangVersion>
    <RestoreAdditionalProjectSources>
      https://api.nuget.org/v3/index.json;
      https://nuget.bepinex.dev/v3/index.json;
      https://nuget.samboy.dev/v3/index.json
    </RestoreAdditionalProjectSources>
    <RootNamespace>WeNeedMoreNoels</RootNamespace>
    <OutputPath>$(GameRootPath)\BepInEx\plugins\WNMN</OutputPath>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <AppendRuntimeIdentifierToOutputPath>false</AppendRuntimeIdentifierToOutputPath>
	<CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
  </PropertyGroup>

  <PropertyGroup>
	<GameAssembliesPath>$(GameRootPath)\AliceInCradle_Data\Managed</GameAssembliesPath>
  </PropertyGroup>
    
  <ItemGroup>
    <PackageReference Include="BepInEx.Analyzers" Version="1.*" PrivateAssets="all" />
    <PackageReference Include="BepInEx.Unity.Mono" Version="6.0.0-be.*" IncludeAssets="compile" />
    <PackageReference Include="BepInEx.PluginInfoProps" Version="2.*" />
    <PackageReference Include="LiteNetLib" Version="0.9.5.2" />
    <PackageReference Include="protobuf-net" Version="2.4.9" />
    <PackageReference Include="System.Reflection" Version="4.3.0" />
    <PackageReference Include="UnityEngine.Modules" Version="2022.3.62" IncludeAssets="compile" />
    <PackageReference Include="Krafs.Publicizer" Version="2.3.0" PrivateAssets="all" />
  </ItemGroup>
  
  <ItemGroup>
    <Publicize Include="Assembly-CSharp" />
    <Publicize Include="unsafeAssem" />
    <Publicize Include="ttr" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="Assembly-CSharp">
      <HintPath>$(GameAssembliesPath)\Assembly-CSharp.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="Fusion.Common">
      <HintPath>$(GameAssembliesPath)\Fusion.Common.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="Fusion.Runtime">
      <HintPath>$(GameAssembliesPath)\Fusion.Runtime.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="Newtonsoft.Json">
      <HintPath>$(GameAssembliesPath)\Newtonsoft.Json.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="pixelliner">
      <HintPath>$(GameAssembliesPath)\pixelliner.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="unsafeAssem">
      <HintPath>$(GameAssembliesPath)\unsafeAssem.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="better">
      <HintPath>$(GameAssembliesPath)\better.dll</HintPath>
      <Private>False</Private>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <None Update="en\en_wnmn_localization.txt">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="pxls\noel_inverse.pxl.dat">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="pxls\noel_inverse.manifest">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="pxls\noel_inverse.pxl.manifest">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="pxls\noel_inverse.pxls.bytes.texture_0.dat">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="pxls\noel_inverse.pxls.bytes.texture_0.manifest">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="pxls\noel_inverse.pxls.dat">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="pxls\noel_inverse.pxls.manifest">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="pxls\noel_inverse_magic.pxl.dat">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="pxls\noel_inverse_magic.manifest">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="pxls\noel_inverse_magic.pxl.manifest">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="pxls\noel_inverse_magic.pxls.bytes.texture_0.dat">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="pxls\noel_inverse_magic.pxls.bytes.texture_0.manifest">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="pxls\noel_inverse_magic.pxls.dat">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="pxls\noel_inverse_magic.pxls.manifest">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="pxls\noel_inverse_r18.pxl.dat">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="pxls\noel_inverse_r18.manifest">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="pxls\noel_inverse_r18.pxl.manifest">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="pxls\noel_inverse_r18.pxls.bytes.texture_0.dat">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="pxls\noel_inverse_r18.pxls.bytes.texture_0.manifest">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="pxls\noel_inverse_r18.pxls.dat">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="pxls\noel_inverse_r18.pxls.manifest">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="pxls\noel_magic_blue.pxls.bytes.texture_0.dat">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="pxls\noel_magic_blue.pxls.bytes.texture_0.manifest">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="pxls\noel_magic_blue.pxls.dat">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="pxls\noel_magic_blue.pxls.manifest">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="pxls\noel_magic_cyan.pxls.bytes.texture_0.dat">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="pxls\noel_magic_cyan.pxls.bytes.texture_0.manifest">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="pxls\noel_magic_cyan.pxls.dat">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="pxls\noel_magic_cyan.pxls.manifest">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="pxls\noel_magic_green.pxls.bytes.texture_0.dat">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="pxls\noel_magic_green.pxls.bytes.texture_0.manifest">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="pxls\noel_magic_green.pxls.dat">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="pxls\noel_magic_green.pxls.manifest">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="pxls\noel_magic_orange.pxls.bytes.texture_0.dat">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="pxls\noel_magic_orange.pxls.bytes.texture_0.manifest">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="pxls\noel_magic_orange.pxls.dat">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="pxls\noel_magic_orange.pxls.manifest">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="pxls\noel_magic_pink.pxls.bytes.texture_0.dat">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="pxls\noel_magic_pink.pxls.bytes.texture_0.manifest">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="pxls\noel_magic_pink.pxls.dat">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="pxls\noel_magic_pink.pxls.manifest">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="pxls\noel_magic_purple.pxls.bytes.texture_0.dat">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="pxls\noel_magic_purple.pxls.bytes.texture_0.manifest">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="pxls\noel_magic_purple.pxls.dat">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="pxls\noel_magic_purple.pxls.manifest">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="pxls\noel_magic_red.pxls.bytes.texture_0.dat">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="pxls\noel_magic_red.pxls.bytes.texture_0.manifest">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="pxls\noel_magic_red.pxls.dat">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="pxls\noel_magic_red.pxls.manifest">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="pxls\noel_magic_yellow.pxls.bytes.texture_0.dat">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="pxls\noel_magic_yellow.pxls.bytes.texture_0.manifest">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="pxls\noel_magic_yellow.pxls.dat">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="pxls\noel_magic_yellow.pxls.manifest">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="resources\multiplayer.dat">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="resources\multiplayer.manifest">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="zh-cn\zh-cn_wnmn_localization.txt">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="zh-tc\zh-tc_wnmn_localization.txt">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>

  <ItemGroup>
    <Folder Include="pxls\" />
  </ItemGroup>
</Project>
