syntax = "proto3";

option csharp_namespace = "WeNeedMoreNoels.DataStruct";

import "updates.proto";

message WNMNPeerMessage {
    int32 peer_id = 1;
    WNMNPeerMessageType type = 2;
    oneof message_content {
        bool place_holder = 3;
        UpdateNoelInfo update_noel_info = 4;
        UpdateNoelState update_noel_state = 5;
        UpdateNoelDamage update_noel_damage = 6;
    }
}

enum WNMNPeerMessageType {
    update_noel_info = 0;
    update_noel_state = 1;
    update_noel_damage = 2;
    notify_change_map_before = 3;
    notify_change_map_after = 4;
}