// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: message.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace WeNeedMoreNoels.DataStruct {

  /// <summary>Holder for reflection information generated from message.proto</summary>
  public static partial class MessageReflection {

    #region Descriptor
    /// <summary>File descriptor for message.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static MessageReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cg1tZXNzYWdlLnByb3RvGg11cGRhdGVzLnByb3RvIv4BCg9XTk1OUGVlck1l",
            "c3NhZ2USDwoHcGVlcl9pZBgBIAEoBRIiCgR0eXBlGAIgASgOMhQuV05NTlBl",
            "ZXJNZXNzYWdlVHlwZRIWCgxwbGFjZV9ob2xkZXIYAyABKAhIABIrChB1cGRh",
            "dGVfbm9lbF9pbmZvGAQgASgLMg8uVXBkYXRlTm9lbEluZm9IABItChF1cGRh",
            "dGVfbm9lbF9zdGF0ZRgFIAEoCzIQLlVwZGF0ZU5vZWxTdGF0ZUgAEi8KEnVw",
            "ZGF0ZV9ub2VsX2RhbWFnZRgGIAEoCzIRLlVwZGF0ZU5vZWxEYW1hZ2VIAEIR",
            "Cg9tZXNzYWdlX2NvbnRlbnQqlQEKE1dOTU5QZWVyTWVzc2FnZVR5cGUSFAoQ",
            "dXBkYXRlX25vZWxfaW5mbxAAEhUKEXVwZGF0ZV9ub2VsX3N0YXRlEAESFgoS",
            "dXBkYXRlX25vZWxfZGFtYWdlEAISHAoYbm90aWZ5X2NoYW5nZV9tYXBfYmVm",
            "b3JlEAMSGwoXbm90aWZ5X2NoYW5nZV9tYXBfYWZ0ZXIQBEIdqgIaV2VOZWVk",
            "TW9yZU5vZWxzLkRhdGFTdHJ1Y3RiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::WeNeedMoreNoels.DataStruct.UpdatesReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::WeNeedMoreNoels.DataStruct.WNMNPeerMessageType), }, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::WeNeedMoreNoels.DataStruct.WNMNPeerMessage), global::WeNeedMoreNoels.DataStruct.WNMNPeerMessage.Parser, new[]{ "PeerId", "Type", "PlaceHolder", "UpdateNoelInfo", "UpdateNoelState", "UpdateNoelDamage" }, new[]{ "MessageContent" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Enums
  public enum WNMNPeerMessageType {
    [pbr::OriginalName("update_noel_info")] UpdateNoelInfo = 0,
    [pbr::OriginalName("update_noel_state")] UpdateNoelState = 1,
    [pbr::OriginalName("update_noel_damage")] UpdateNoelDamage = 2,
    [pbr::OriginalName("notify_change_map_before")] NotifyChangeMapBefore = 3,
    [pbr::OriginalName("notify_change_map_after")] NotifyChangeMapAfter = 4,
  }

  #endregion

  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class WNMNPeerMessage : pb::IMessage<WNMNPeerMessage>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<WNMNPeerMessage> _parser = new pb::MessageParser<WNMNPeerMessage>(() => new WNMNPeerMessage());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<WNMNPeerMessage> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::WeNeedMoreNoels.DataStruct.MessageReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public WNMNPeerMessage() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public WNMNPeerMessage(WNMNPeerMessage other) : this() {
      peerId_ = other.peerId_;
      type_ = other.type_;
      switch (other.MessageContentCase) {
        case MessageContentOneofCase.PlaceHolder:
          PlaceHolder = other.PlaceHolder;
          break;
        case MessageContentOneofCase.UpdateNoelInfo:
          UpdateNoelInfo = other.UpdateNoelInfo.Clone();
          break;
        case MessageContentOneofCase.UpdateNoelState:
          UpdateNoelState = other.UpdateNoelState.Clone();
          break;
        case MessageContentOneofCase.UpdateNoelDamage:
          UpdateNoelDamage = other.UpdateNoelDamage.Clone();
          break;
      }

      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public WNMNPeerMessage Clone() {
      return new WNMNPeerMessage(this);
    }

    /// <summary>Field number for the "peer_id" field.</summary>
    public const int PeerIdFieldNumber = 1;
    private int peerId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int PeerId {
      get { return peerId_; }
      set {
        peerId_ = value;
      }
    }

    /// <summary>Field number for the "type" field.</summary>
    public const int TypeFieldNumber = 2;
    private global::WeNeedMoreNoels.DataStruct.WNMNPeerMessageType type_ = global::WeNeedMoreNoels.DataStruct.WNMNPeerMessageType.UpdateNoelInfo;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::WeNeedMoreNoels.DataStruct.WNMNPeerMessageType Type {
      get { return type_; }
      set {
        type_ = value;
      }
    }

    /// <summary>Field number for the "place_holder" field.</summary>
    public const int PlaceHolderFieldNumber = 3;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool PlaceHolder {
      get { return HasPlaceHolder ? (bool) messageContent_ : false; }
      set {
        messageContent_ = value;
        messageContentCase_ = MessageContentOneofCase.PlaceHolder;
      }
    }
    /// <summary>Gets whether the "place_holder" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasPlaceHolder {
      get { return messageContentCase_ == MessageContentOneofCase.PlaceHolder; }
    }
    /// <summary> Clears the value of the oneof if it's currently set to "place_holder" </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearPlaceHolder() {
      if (HasPlaceHolder) {
        ClearMessageContent();
      }
    }

    /// <summary>Field number for the "update_noel_info" field.</summary>
    public const int UpdateNoelInfoFieldNumber = 4;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::WeNeedMoreNoels.DataStruct.UpdateNoelInfo UpdateNoelInfo {
      get { return messageContentCase_ == MessageContentOneofCase.UpdateNoelInfo ? (global::WeNeedMoreNoels.DataStruct.UpdateNoelInfo) messageContent_ : null; }
      set {
        messageContent_ = value;
        messageContentCase_ = value == null ? MessageContentOneofCase.None : MessageContentOneofCase.UpdateNoelInfo;
      }
    }

    /// <summary>Field number for the "update_noel_state" field.</summary>
    public const int UpdateNoelStateFieldNumber = 5;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::WeNeedMoreNoels.DataStruct.UpdateNoelState UpdateNoelState {
      get { return messageContentCase_ == MessageContentOneofCase.UpdateNoelState ? (global::WeNeedMoreNoels.DataStruct.UpdateNoelState) messageContent_ : null; }
      set {
        messageContent_ = value;
        messageContentCase_ = value == null ? MessageContentOneofCase.None : MessageContentOneofCase.UpdateNoelState;
      }
    }

    /// <summary>Field number for the "update_noel_damage" field.</summary>
    public const int UpdateNoelDamageFieldNumber = 6;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::WeNeedMoreNoels.DataStruct.UpdateNoelDamage UpdateNoelDamage {
      get { return messageContentCase_ == MessageContentOneofCase.UpdateNoelDamage ? (global::WeNeedMoreNoels.DataStruct.UpdateNoelDamage) messageContent_ : null; }
      set {
        messageContent_ = value;
        messageContentCase_ = value == null ? MessageContentOneofCase.None : MessageContentOneofCase.UpdateNoelDamage;
      }
    }

    private object messageContent_;
    /// <summary>Enum of possible cases for the "message_content" oneof.</summary>
    public enum MessageContentOneofCase {
      None = 0,
      PlaceHolder = 3,
      UpdateNoelInfo = 4,
      UpdateNoelState = 5,
      UpdateNoelDamage = 6,
    }
    private MessageContentOneofCase messageContentCase_ = MessageContentOneofCase.None;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public MessageContentOneofCase MessageContentCase {
      get { return messageContentCase_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearMessageContent() {
      messageContentCase_ = MessageContentOneofCase.None;
      messageContent_ = null;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as WNMNPeerMessage);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(WNMNPeerMessage other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (PeerId != other.PeerId) return false;
      if (Type != other.Type) return false;
      if (PlaceHolder != other.PlaceHolder) return false;
      if (!object.Equals(UpdateNoelInfo, other.UpdateNoelInfo)) return false;
      if (!object.Equals(UpdateNoelState, other.UpdateNoelState)) return false;
      if (!object.Equals(UpdateNoelDamage, other.UpdateNoelDamage)) return false;
      if (MessageContentCase != other.MessageContentCase) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (PeerId != 0) hash ^= PeerId.GetHashCode();
      if (Type != global::WeNeedMoreNoels.DataStruct.WNMNPeerMessageType.UpdateNoelInfo) hash ^= Type.GetHashCode();
      if (HasPlaceHolder) hash ^= PlaceHolder.GetHashCode();
      if (messageContentCase_ == MessageContentOneofCase.UpdateNoelInfo) hash ^= UpdateNoelInfo.GetHashCode();
      if (messageContentCase_ == MessageContentOneofCase.UpdateNoelState) hash ^= UpdateNoelState.GetHashCode();
      if (messageContentCase_ == MessageContentOneofCase.UpdateNoelDamage) hash ^= UpdateNoelDamage.GetHashCode();
      hash ^= (int) messageContentCase_;
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (PeerId != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(PeerId);
      }
      if (Type != global::WeNeedMoreNoels.DataStruct.WNMNPeerMessageType.UpdateNoelInfo) {
        output.WriteRawTag(16);
        output.WriteEnum((int) Type);
      }
      if (HasPlaceHolder) {
        output.WriteRawTag(24);
        output.WriteBool(PlaceHolder);
      }
      if (messageContentCase_ == MessageContentOneofCase.UpdateNoelInfo) {
        output.WriteRawTag(34);
        output.WriteMessage(UpdateNoelInfo);
      }
      if (messageContentCase_ == MessageContentOneofCase.UpdateNoelState) {
        output.WriteRawTag(42);
        output.WriteMessage(UpdateNoelState);
      }
      if (messageContentCase_ == MessageContentOneofCase.UpdateNoelDamage) {
        output.WriteRawTag(50);
        output.WriteMessage(UpdateNoelDamage);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (PeerId != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(PeerId);
      }
      if (Type != global::WeNeedMoreNoels.DataStruct.WNMNPeerMessageType.UpdateNoelInfo) {
        output.WriteRawTag(16);
        output.WriteEnum((int) Type);
      }
      if (HasPlaceHolder) {
        output.WriteRawTag(24);
        output.WriteBool(PlaceHolder);
      }
      if (messageContentCase_ == MessageContentOneofCase.UpdateNoelInfo) {
        output.WriteRawTag(34);
        output.WriteMessage(UpdateNoelInfo);
      }
      if (messageContentCase_ == MessageContentOneofCase.UpdateNoelState) {
        output.WriteRawTag(42);
        output.WriteMessage(UpdateNoelState);
      }
      if (messageContentCase_ == MessageContentOneofCase.UpdateNoelDamage) {
        output.WriteRawTag(50);
        output.WriteMessage(UpdateNoelDamage);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (PeerId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(PeerId);
      }
      if (Type != global::WeNeedMoreNoels.DataStruct.WNMNPeerMessageType.UpdateNoelInfo) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Type);
      }
      if (HasPlaceHolder) {
        size += 1 + 1;
      }
      if (messageContentCase_ == MessageContentOneofCase.UpdateNoelInfo) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(UpdateNoelInfo);
      }
      if (messageContentCase_ == MessageContentOneofCase.UpdateNoelState) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(UpdateNoelState);
      }
      if (messageContentCase_ == MessageContentOneofCase.UpdateNoelDamage) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(UpdateNoelDamage);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(WNMNPeerMessage other) {
      if (other == null) {
        return;
      }
      if (other.PeerId != 0) {
        PeerId = other.PeerId;
      }
      if (other.Type != global::WeNeedMoreNoels.DataStruct.WNMNPeerMessageType.UpdateNoelInfo) {
        Type = other.Type;
      }
      switch (other.MessageContentCase) {
        case MessageContentOneofCase.PlaceHolder:
          PlaceHolder = other.PlaceHolder;
          break;
        case MessageContentOneofCase.UpdateNoelInfo:
          if (UpdateNoelInfo == null) {
            UpdateNoelInfo = new global::WeNeedMoreNoels.DataStruct.UpdateNoelInfo();
          }
          UpdateNoelInfo.MergeFrom(other.UpdateNoelInfo);
          break;
        case MessageContentOneofCase.UpdateNoelState:
          if (UpdateNoelState == null) {
            UpdateNoelState = new global::WeNeedMoreNoels.DataStruct.UpdateNoelState();
          }
          UpdateNoelState.MergeFrom(other.UpdateNoelState);
          break;
        case MessageContentOneofCase.UpdateNoelDamage:
          if (UpdateNoelDamage == null) {
            UpdateNoelDamage = new global::WeNeedMoreNoels.DataStruct.UpdateNoelDamage();
          }
          UpdateNoelDamage.MergeFrom(other.UpdateNoelDamage);
          break;
      }

      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            PeerId = input.ReadInt32();
            break;
          }
          case 16: {
            Type = (global::WeNeedMoreNoels.DataStruct.WNMNPeerMessageType) input.ReadEnum();
            break;
          }
          case 24: {
            PlaceHolder = input.ReadBool();
            break;
          }
          case 34: {
            global::WeNeedMoreNoels.DataStruct.UpdateNoelInfo subBuilder = new global::WeNeedMoreNoels.DataStruct.UpdateNoelInfo();
            if (messageContentCase_ == MessageContentOneofCase.UpdateNoelInfo) {
              subBuilder.MergeFrom(UpdateNoelInfo);
            }
            input.ReadMessage(subBuilder);
            UpdateNoelInfo = subBuilder;
            break;
          }
          case 42: {
            global::WeNeedMoreNoels.DataStruct.UpdateNoelState subBuilder = new global::WeNeedMoreNoels.DataStruct.UpdateNoelState();
            if (messageContentCase_ == MessageContentOneofCase.UpdateNoelState) {
              subBuilder.MergeFrom(UpdateNoelState);
            }
            input.ReadMessage(subBuilder);
            UpdateNoelState = subBuilder;
            break;
          }
          case 50: {
            global::WeNeedMoreNoels.DataStruct.UpdateNoelDamage subBuilder = new global::WeNeedMoreNoels.DataStruct.UpdateNoelDamage();
            if (messageContentCase_ == MessageContentOneofCase.UpdateNoelDamage) {
              subBuilder.MergeFrom(UpdateNoelDamage);
            }
            input.ReadMessage(subBuilder);
            UpdateNoelDamage = subBuilder;
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            PeerId = input.ReadInt32();
            break;
          }
          case 16: {
            Type = (global::WeNeedMoreNoels.DataStruct.WNMNPeerMessageType) input.ReadEnum();
            break;
          }
          case 24: {
            PlaceHolder = input.ReadBool();
            break;
          }
          case 34: {
            global::WeNeedMoreNoels.DataStruct.UpdateNoelInfo subBuilder = new global::WeNeedMoreNoels.DataStruct.UpdateNoelInfo();
            if (messageContentCase_ == MessageContentOneofCase.UpdateNoelInfo) {
              subBuilder.MergeFrom(UpdateNoelInfo);
            }
            input.ReadMessage(subBuilder);
            UpdateNoelInfo = subBuilder;
            break;
          }
          case 42: {
            global::WeNeedMoreNoels.DataStruct.UpdateNoelState subBuilder = new global::WeNeedMoreNoels.DataStruct.UpdateNoelState();
            if (messageContentCase_ == MessageContentOneofCase.UpdateNoelState) {
              subBuilder.MergeFrom(UpdateNoelState);
            }
            input.ReadMessage(subBuilder);
            UpdateNoelState = subBuilder;
            break;
          }
          case 50: {
            global::WeNeedMoreNoels.DataStruct.UpdateNoelDamage subBuilder = new global::WeNeedMoreNoels.DataStruct.UpdateNoelDamage();
            if (messageContentCase_ == MessageContentOneofCase.UpdateNoelDamage) {
              subBuilder.MergeFrom(UpdateNoelDamage);
            }
            input.ReadMessage(subBuilder);
            UpdateNoelDamage = subBuilder;
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
